const data = [
  [
    {
      keyCode: 'KeyA',
      caseDownEn: 'a',
      caseUpEn: 'A',
      capsEn: 'A',
      shiftcapsEn: 'a',
    },
    {
      keyCode: 'KeyB',
      caseDownEn: 'b',
      caseUpEn: 'B',
      capsEn: 'B',
      shiftcapsEn: 'b',
    },
    {
      keyCode: 'KeyC',
      caseDownEn: 'c',
      caseUpEn: 'C',
      capsEn: 'C',
      shiftcapsEn: 'c',
    },
    {
      keyCode: 'KeyD',
      caseDownEn: 'd',
      caseUpEn: 'D',
      capsEn: 'D',
      shiftcapsEn: 'd',
    },
    {
      keyCode: 'KeyE',
      caseDownEn: 'e',
      caseUpEn: 'E',
      capsEn: 'E',
      shiftcapsEn: 'e',
    },
    {
      keyCode: 'KeyF',
      caseDownEn: 'f',
      caseUpEn: 'F',
      capsEn: 'F',
      shiftcapsEn: 'f',
    },
    {
      keyCode: 'KeyG',
      caseDownEn: 'g',
      caseUpEn: 'G',
      capsEn: 'G',
      shiftcapsEn: 'g',
    },
    {
      keyCode: 'KeyH',
      caseDownEn: 'h',
      caseUpEn: 'H',
      capsEn: 'H',
      shiftcapsEn: 'h',
    },
    {
      keyCode: 'KeyI',
      caseDownEn: 'i',
      caseUpEn: 'I',
      capsEn: 'I',
      shiftcapsEn: 'i',
    },
  ],
  [
    {
      keyCode: 'KeyJ',
      caseDownEn: 'j',
      caseUpEn: 'J',
      capsEn: 'J',
      shiftcapsEn: 'j',
    },
    {
      keyCode: 'KeyK',
      caseDownEn: 'k',
      caseUpEn: 'K',
      capsEn: 'K',
      shiftcapsEn: 'k',
    },
    {
      keyCode: 'KeyL',
      caseDownEn: 'l',
      caseUpEn: 'L',
      capsEn: 'L',
      shiftcapsEn: 'l',
    },
    {
      keyCode: 'KeyM',
      caseDownEn: 'm',
      caseUpEn: 'M',
      capsEn: 'M',
      shiftcapsEn: 'm',
    },
    {
      keyCode: 'KeyN',
      caseDownEn: 'n',
      caseUpEn: 'N',
      capsEn: 'N',
      shiftcapsEn: 'n',
    },
    {
      keyCode: 'KeyO',
      caseDownEn: 'o',
      caseUpEn: 'O',
      capsEn: 'O',
      shiftcapsEn: 'o',
    },
    {
      keyCode: 'KeyP',
      caseDownEn: 'p',
      caseUpEn: 'P',
      capsEn: 'P',
      shiftcapsEn: 'p',
    },
    {
      keyCode: 'KeyQ',
      caseDownEn: 'q',
      caseUpEn: 'Q',
      capsEn: 'Q',
      shiftcapsEn: 'q',
    },
    {
      keyCode: 'KeyR',
      caseDownEn: 'r',
      caseUpEn: 'R',
      capsEn: 'R',
      shiftcapsEn: 'r',
    },
  ],
  [
    {
      keyCode: 'KeyS',
      caseDownEn: 's',
      caseUpEn: 'S',
      capsEn: 'S',
      shiftcapsEn: 's',
    },
    {
      keyCode: 'KeyT',
      caseDownEn: 't',
      caseUpEn: 'T',
      capsEn: 'T',
      shiftcapsEn: 't',
    },
    {
      keyCode: 'KeyU',
      caseDownEn: 'u',
      caseUpEn: 'U',
      capsEn: 'U',
      shiftcapsEn: 'u',
    },
    {
      keyCode: 'KeyV',
      caseDownEn: 'v',
      caseUpEn: 'V',
      capsEn: 'V',
      shiftcapsEn: 'v',
    },
    {
      keyCode: 'KeyW',
      caseDownEn: 'w',
      caseUpEn: 'W',
      capsEn: 'W',
      shiftcapsEn: 'w',
    },
    {
      keyCode: 'KeyX',
      caseDownEn: 'x',
      caseUpEn: 'X',
      capsEn: 'X',
      shiftcapsEn: 'x',
    },
    {
      keyCode: 'KeyY',
      caseDownEn: 'y',
      caseUpEn: 'Y',
      capsEn: 'Y',
      shiftcapsEn: 'y',
    },
    {
      keyCode: 'KeyZ',
      caseDownEn: 'z',
      caseUpEn: 'Z',
      capsEn: 'Z',
      shiftcapsEn: 'z',
    },
  ],
];

export default data;
